#!/bin/bash
# init-repo.sh — Initialize the git backup repository
#
# Idempotent: safe to run on an existing repo.
# Called from the PHP UI "Initialize Repo" button or manually.

set -euo pipefail

PLUGIN_DIR="/usr/local/emhttp/plugins/git-backup"
CONFIG="/boot/config/plugins/git-backup/git-backup.cfg"

# Load config (INI format is valid bash KEY="value")
if [ ! -f "$CONFIG" ]; then
    echo "ERROR: Config not found: $CONFIG"
    exit 1
fi
source "$CONFIG"

echo "=== Git Backup Repository Init ==="
echo ""

# 1. Create repo directory
echo "Creating repo directory: $REPO_PATH"
mkdir -p "$REPO_PATH"
cd "$REPO_PATH" || { echo "ERROR: Cannot cd to $REPO_PATH"; exit 1; }

# 2. Init git repo if not already
if [ ! -d ".git" ]; then
    echo "Initializing new git repository..."
    git init
    git checkout -b "$BRANCH" 2>/dev/null || git branch -M "$BRANCH"
else
    echo "Git repository already exists."
fi

# 3. Configure git identity
SERVER_NAME=$(hostname)
git config user.email "git-backup@${SERVER_NAME}.local"
git config user.name "Git Backup (${SERVER_NAME})"
echo "Git identity: Git Backup (${SERVER_NAME}) <git-backup@${SERVER_NAME}.local>"

# 4. Add/update remote if URL provided
if [ -n "$REMOTE_URL" ]; then
    if git remote get-url "$REMOTE_NAME" &>/dev/null; then
        git remote set-url "$REMOTE_NAME" "$REMOTE_URL"
        echo "Updated remote '$REMOTE_NAME' -> $REMOTE_URL"
    else
        git remote add "$REMOTE_NAME" "$REMOTE_URL"
        echo "Added remote '$REMOTE_NAME' -> $REMOTE_URL"
    fi
else
    echo "No remote URL configured. Backups will be local only."
fi

# 5. Create .gitignore
cat > .gitignore << 'GITIGNORE'
# Auto-generated by git-backup plugin
# Safety net — these should already be excluded by backup rules,
# but this prevents accidental commits if files slip through.
*.db
*.db-shm
*.db-wal
*.sqlite
*.sqlite3
*.log
*.pid
*.sock
*.lock

# Vendored third-party code and build caches — not configuration, no restore
# value, and a large false-positive surface for secret scanning. Tune per host.
**/node_modules/
**/site-packages/
**/venv*/
**/__pycache__/

# git-crypt symmetric key — must NEVER be committed to the repo it protects.
git-crypt.key
*.git-crypt-key
GITIGNORE
echo "Created .gitignore"

# 6. Create directory structure
mkdir -p appdata compose haos unraid
echo "Created backup directories: appdata/ compose/ haos/ unraid/"

# 6b. Install the secrets guard (idempotent).
#
# Two layers, because the failure mode is silent: if git-crypt is unavailable
# git's clean filter no-ops, the backup commits real credentials in plaintext,
# and the run still looks successful.
#   Layer 1 — filter.git-crypt.required: git treats a filter failure as fatal,
#             so plaintext never reaches the index at all.
#   Layer 2 — pre-commit hook: catches the case where the filter is configured
#             but did not apply. Never calls git-crypt itself, since the binary
#             being gone is precisely what it guards against.
if [ "${GITCRYPT_ENABLED:-no}" = "yes" ]; then
    git config filter.git-crypt.required true
    echo "Set filter.git-crypt.required=true"

    # Pin to an absolute path when one is configured: `git-crypt init` writes a
    # bare name, which depends on PATH — and on Unraid /usr is rebuilt from RAM
    # every boot, so cron can easily run without it.
    if [ -n "${GITCRYPT_BIN:-}" ] && [ -x "${GITCRYPT_BIN}" ]; then
        git config filter.git-crypt.clean  "$GITCRYPT_BIN clean"
        git config filter.git-crypt.smudge "$GITCRYPT_BIN smudge"
        git config diff.git-crypt.textconv "$GITCRYPT_BIN diff"
        echo "Pinned git-crypt filter to $GITCRYPT_BIN"
    fi
fi

if [ -f "$PLUGIN_DIR/scripts/pre-commit-hook.sh" ]; then
    install -m 0755 "$PLUGIN_DIR/scripts/pre-commit-hook.sh" .git/hooks/pre-commit
    echo "Installed pre-commit secrets guard"
fi

# 7. Initial commit
git add .gitignore
git commit -m "init: git-backup repository" --allow-empty 2>/dev/null
echo ""

# 8. Test push if remote configured
if [ -n "$REMOTE_URL" ] && [ "$PUSH_AFTER_COMMIT" = "yes" ]; then
    echo "Testing push to remote..."
    if git push -u "$REMOTE_NAME" "$BRANCH" 2>&1; then
        echo ""
        echo "SUCCESS: Remote push verified."
    else
        echo ""
        echo "ERROR: Push failed. Check:"
        echo "  1. SSH key exists at the path configured in git-backup settings"
        echo "  2. Key is added to your Git provider (GitHub/GitLab/Gitea)"
        echo "  3. Remote URL is correct: $REMOTE_URL"
        echo ""
        echo "To generate an SSH key:"
        echo "  ssh-keygen -t ed25519 -f /root/.ssh/git_backup_key -N ''"
        echo ""
        echo "Add to ~/.ssh/config:"
        echo "  Host github.com"
        echo "    IdentityFile /root/.ssh/git_backup_key"
        exit 1
    fi
fi

echo ""
echo "=== Init complete ==="
echo "Repository: $REPO_PATH"
echo "Branch: $BRANCH"
[ -n "$REMOTE_URL" ] && echo "Remote: $REMOTE_URL"
echo ""
echo "Run a backup with: /usr/local/emhttp/plugins/git-backup/rc.git-backup run"
echo "Or dry run with:   /usr/local/emhttp/plugins/git-backup/rc.git-backup run --dry-run"
