#!/bin/bash
# init-repo.sh — Initialize the git backup repository
#
# Idempotent: safe to run on an existing repo.
# Called from the PHP UI "Initialize Repo" button or manually.

set -euo pipefail

PLUGIN_DIR="/usr/local/emhttp/plugins/git-backup"
CONFIG="/boot/config/plugins/git-backup/git-backup.cfg"

# Load config (INI format is valid bash KEY="value")
if [ ! -f "$CONFIG" ]; then
    echo "ERROR: Config not found: $CONFIG"
    exit 1
fi
source "$CONFIG"

echo "=== Git Backup Repository Init ==="
echo ""

# 1. Create repo directory
echo "Creating repo directory: $REPO_PATH"
mkdir -p "$REPO_PATH"
cd "$REPO_PATH" || { echo "ERROR: Cannot cd to $REPO_PATH"; exit 1; }

# 2. Init git repo if not already
if [ ! -d ".git" ]; then
    echo "Initializing new git repository..."
    git init
    git checkout -b "$BRANCH" 2>/dev/null || git branch -M "$BRANCH"
else
    echo "Git repository already exists."
fi

# 3. Configure git identity
SERVER_NAME=$(hostname)
git config user.email "git-backup@${SERVER_NAME}.local"
git config user.name "Git Backup (${SERVER_NAME})"
echo "Git identity: Git Backup (${SERVER_NAME}) <git-backup@${SERVER_NAME}.local>"

# 4. Add/update remote if URL provided
if [ -n "$REMOTE_URL" ]; then
    if git remote get-url "$REMOTE_NAME" &>/dev/null; then
        git remote set-url "$REMOTE_NAME" "$REMOTE_URL"
        echo "Updated remote '$REMOTE_NAME' -> $REMOTE_URL"
    else
        git remote add "$REMOTE_NAME" "$REMOTE_URL"
        echo "Added remote '$REMOTE_NAME' -> $REMOTE_URL"
    fi
else
    echo "No remote URL configured. Backups will be local only."
fi

# 5. Create .gitignore
cat > .gitignore << 'GITIGNORE'
# Auto-generated by git-backup plugin
# Safety net — these should already be excluded by backup rules,
# but this prevents accidental commits if files slip through.
*.db
*.db-shm
*.db-wal
*.sqlite
*.sqlite3
*.log
*.pid
*.sock
*.lock
GITIGNORE
echo "Created .gitignore"

# 6. Create directory structure
mkdir -p appdata compose haos unraid
echo "Created backup directories: appdata/ compose/ haos/ unraid/"

# 7. Initial commit
git add .gitignore
git commit -m "init: git-backup repository" --allow-empty 2>/dev/null
echo ""

# 8. Test push if remote configured
if [ -n "$REMOTE_URL" ] && [ "$PUSH_AFTER_COMMIT" = "yes" ]; then
    echo "Testing push to remote..."
    if git push -u "$REMOTE_NAME" "$BRANCH" 2>&1; then
        echo ""
        echo "SUCCESS: Remote push verified."
    else
        echo ""
        echo "ERROR: Push failed. Check:"
        echo "  1. SSH key exists at the path configured in git-backup settings"
        echo "  2. Key is added to your Git provider (GitHub/GitLab/Gitea)"
        echo "  3. Remote URL is correct: $REMOTE_URL"
        echo ""
        echo "To generate an SSH key:"
        echo "  ssh-keygen -t ed25519 -f /root/.ssh/git_backup_key -N ''"
        echo ""
        echo "Add to ~/.ssh/config:"
        echo "  Host github.com"
        echo "    IdentityFile /root/.ssh/git_backup_key"
        exit 1
    fi
fi

echo ""
echo "=== Init complete ==="
echo "Repository: $REPO_PATH"
echo "Branch: $BRANCH"
[ -n "$REMOTE_URL" ] && echo "Remote: $REMOTE_URL"
echo ""
echo "Run a backup with: /usr/local/emhttp/plugins/git-backup/rc.git-backup run"
echo "Or dry run with:   /usr/local/emhttp/plugins/git-backup/rc.git-backup run --dry-run"
